# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-05-24 14:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fhrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhrs_id', models.IntegerField(unique=True)),
                ('business_name', models.TextField(blank=True, null=True)),
                ('business_type', models.TextField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('address_line3', models.TextField(blank=True, null=True)),
                ('address_line4', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
