# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0006_auto_20160607_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('flag', models.CharField(choices=[('not a school', 'Not a school'), ('no school data', 'No data found for nearby schools'), ('already in osm', 'Is already mapped in OSM'), ('not accurate', 'The data is not accurate enough')], default=None, max_length=32)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.EducationSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
