# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdubaseSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Edubase')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.FunctionalSite')),
            ],
        ),
        migrations.CreateModel(
            name='SeedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SeedData')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.FunctionalSite')),
            ],
        ),
    ]
