# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.FunctionalSite')),
            ],
        ),
        migrations.RemoveField(
            model_name='edubasesite',
            name='school',
        ),
        migrations.RemoveField(
            model_name='edubasesite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='seedsite',
            name='school',
        ),
        migrations.RemoveField(
            model_name='seedsite',
            name='site',
        ),
        migrations.DeleteModel(
            name='EdubaseSite',
        ),
        migrations.DeleteModel(
            name='SeedSite',
        ),
        migrations.AlterUniqueTogether(
            name='schoolsite',
            unique_together=set([('school', 'site')]),
        ),
    ]
